apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: $(PROJECT_NAME)-sg
  name: $(PROJECT_NAME)-sg
  namespace: $(NAMESPACE)-sg
  selfLink: /apis/apps.openshift.io/v1/namespaces/$(NAMESPACE)-sg/deploymentconfigs/$(PROJECT_NAME)-sg
spec:
  replicas: 1
  selector:
    app: $(PROJECT_NAME)-sg
    deploymentconfig: $(PROJECT_NAME)-sg
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 180
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      labels:
        app: $(PROJECT_NAME)-sg
        deploymentconfig: $(PROJECT_NAME)-sg
    spec:
      containers:
        - envFrom:
            - configMapRef:
                name: $(PROJECT_NAME)-sg
          image: docker-registry.default.svc:5000/$(NAMESPACE)-sg/$(PROJECT_NAME)-sg:1.0
          imagePullPolicy: Always
          name: $(PROJECT_NAME)-sg
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          ports:
            - containerPort: 8443
              protocol: TCP
          securityContext:
            runAsUser: 1000710000
            supplementalGroups:
              - 1000770000
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /$(NAMESPACE)-sg
              name: $(NAMESPACE)-sg-pv
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: $(NAMESPACE)-sg-pv
          persistentVolumeClaim:
            claimName: $(NAMESPACE)-sg-pvc
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - $(PROJECT_NAME)-sg
        from:
          kind: ImageStreamTag
          name: '$(PROJECT_NAME)-sg:1.0'
          namespace: $(NAMESPACE)-sg
        lastTriggeredImage: docker-registry.default.svc:5000/$(NAMESPACE)-sg/$(PROJECT_NAME)-sg:1.0
      type: ImageChange
to:
  apiVersion: v1
  kind: Service
  name: $(PROJECT_NAME)-sg
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    labels:
      app: $(PROJECT_NAME)-sg
    name: $(PROJECT_NAME)-sg
    namespace: $(NAMESPACE)-sg
  spec:
    ports:
      - name: 8443-tcp
        port: 8443
        protocol: TCP
        targetPort: 8443
    selector:
      deploymentconfig: $(PROJECT_NAME)-sg
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}