# This is a basic workflow to help you get started with Actions

name: Package for deployment into CMS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master", "cicd-master-*", "cicd-init-*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  pre:
    name: sending message
    runs-on: rd-hosted
    outputs:
      slack_output: ${{ steps.slack.outputs.ts }}
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ secrets.SLACK_CSL_CHANNEL }}
          payload: |
            {
              "text": "${{ github.event.head_commit.author.name }} - ${{ github.repository }} - ${{ github.ref }} - ${{ github.sha }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ github.event.head_commit.author.name }} - ${{ github.repository }} - started"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "${{ github.ref }} - ${{ github.sha }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          
  staging:
    # The type of runner that the job will run on
    runs-on: rd-hosted
    needs: [pre]
    name: Build and upload to staging
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.17.1
          registry-url: ${{ secrets.NPM_PATH }}
      - name: Build files...
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          node -v
          npm -v
          npm install
          npm build:staging
      - name: 📂 Upload build folder to staging
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SERVER_USER_NAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          server: ${{ secrets.SERVER_HOST }}
          local_path: './dist/*'
          remote_path: ${{ secrets.SERVER_REMOTE_PATH_OCBCEXT1 }}
          sftp_only: true
          
  build_zip_upload:
    # The type of runner that the job will run on
    runs-on: self-hosted
    needs: [pre]
    name: Build, zip and upload production package
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.17.1
          registry-url: ${{ secrets.NPM_PATH }}
      - name: Build files...
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          node -v
          npm -v
          npm install
          npm build:production

      - name: Zip folder
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r glf-prod-${{ github.sha }}.zip ./dist

      - name: 📂 Sync files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SERVER_USER_NAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          server: ${{ secrets.SERVER_HOST }}
          local_path: 'glf-prod-${{ github.sha }}.zip'
          remote_path: ${{ secrets.SERVER_REMOTE_PATH_PACKAGE }}
          sftp_only: true

  slack:
    name: sending slack message
    if: ${{ always() }}
    needs: [build_zip_upload, staging, pre]
    runs-on: self-hosted
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.22.0
        with:
          channel-id: ${{ secrets.SLACK_CSL_CHANNEL }}
          update-ts: ${{ needs.pre.outputs.slack_output }}
          payload: |
            {
              "text": "GitHub ${{ github.repository }} - ${{ github.ref }} - ${{ github.sha }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ github.actor }} - ${{ github.repository }} - finished"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Staging: ${{ needs.staging.result }}\nPackage: ${{ needs.build_zip_upload.result }}\nDownload https://files.ext1.wearesection.com/package/glf-prod-${{ github.sha }}.zip"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "${{ github.ref }} - *<${{ github.event.pull_request.html_url || github.event.head_commit.url }}|${{ github.sha }}>*"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}